### PR TITLE
Use full action "drop" for logs

### PR DESCRIPTION
**Pull request by elemoine**
DO NOT MERGE.

I am just creating this for discussion.

### CODE REVIEW

**Review by SwannCroiset — CHANGES_REQUESTED** [review]
This is very sad to come up with a drop policy :(
I'd instead try to fix the responsible filter

**Comment by simonpasquier** [comment]
In the short term, I think it is the right decision. We know that by design, re-injecting messages in the pipeline is a bad pattern so in the longer term, I would explore moving the filters logic to the decoders wherever this is possible.

**Comment by elemoine** [comment]
> In the short term, I think it is the right decision. We know that by design, re-injecting messages in the pipeline is a bad pattern so in the longer term, I would explore moving the filters logic to the decoders wherever this is possible.

Agree. Feel free to approve the PR then :)

**Comment by ppetit** [comment]
Will have to refactor this a.s.a.p because dropping logs is really, really bad. I'll create a Jira ticket to mark it as priority fix.

**Comment by SwannCroiset** [comment]
> Will have to refactor this a.s.a.p because dropping logs is really, really bad. I'll create a Jira ticket to mark it as priority fix.

I'm doing some tests currently and nearly found out a way to avoid this kind of dead lock

**Comment by SwannCroiset** [comment]
> I would explore moving the filters logic to the decoders wherever this is possible.

This is not possible to move the logic into the decoders since there is no timer_event() function there.
The only option we have is to rework the filter log_counter sending bulk_metric every minute in place of filling the Heka router by injecting several message (10) potentially every second.

I don't block the PR if you want merge it

**Review by simonpasquier — APPROVED** [review]

**Comment by simonpasquier** [comment]
Merging this as a temporary workaround. We'll be working on a more satisfying bug fix ASAP.

**Pull request merged**
