### PR TITLE
Make INFO the default syslog severity level

### PR DESCRIPTION
**Pull request by SwannCroiset**
Otherwise the severity is DEBUG.

### CODE REVIEW

**Review by elemoine — APPROVED** [review]

**Review by simonpasquier — CHANGES_REQUESTED** [review]
Let's rather fix the rsyslog configuration.

**Comment by SwannCroiset** [comment]
> Let's rather fix the rsyslog configuration.

and are you working on it ?

**Review by simonpasquier — APPROVED** [review]

**Comment by simonpasquier** [comment]
I've opened a bug to track the root problem.

**Comment by gthvn1** [comment]
Souldn't be done in lma_utils.lua ? 
here: 75 local default_severity = 7

**Pull request merged**
