### PR TITLE
Fix unclosed condition in ceilometer heka config

### PR DESCRIPTION
**Pull request by dkalashnik**
Just remove the useless one

### CODE REVIEW

**Comment by cloudlab-autobuild** [comment]
Can one of the admins verify this patch?

**Comment by cznewt** [comment]
please better add the ending {% endif %}  to fix this :) and make PR to master

**Review by cznewt — CHANGES_REQUESTED** [review]
add endif

**Comment by dkalashnik** [comment]
Done, closing this one PR

**Pull request closed without merging**
